id: 0c9857b9-4dc7-42df-a1b9-e18b9ba6c255
name: First Test App
description: First application for testing ZIP export
auth_flow_graph_id: auth_flow_config_basic
registration_flow_graph_id: registration_flow_config_basic
is_registration_flow_enabled: true
url: https://localhost:3001
token:
  issuer: thunder
  validity_period: 3600
certificate:
  type: NONE
inbound_auth_config:
  - config:
      client_id: {{.FIRST_TEST_APP_CLIENT_ID}}
      client_secret: {{.FIRST_TEST_APP_CLIENT_SECRET}}
      redirect_uris:
        {{- range .FIRST_TEST_APP_REDIRECT_URIS}}
        - {{.}}
        {{- end}}
      grant_types:
        - authorization_code
      response_types:
        - code
      token_endpoint_auth_method: client_secret_basic
      pkce_required: false
      public_client: false
      token:
        issuer: thunder
        access_token:
          validity_period: 3600
        id_token:
          validity_period: 3600